import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Image, Alert, ActivityIndicator } from 'react-native';
import { ScreenWrapper } from '../components/ScreenWrapper';
import { COLORS, FONTS, SHADOWS } from '../constants/theme';
import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import Animated, { FadeInUp } from 'react-native-reanimated';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { API_ENDPOINTS } from '../services/api.config';

export const AnalysisScreen = () => {
    const [image, setImage] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [analysis, setAnalysis] = useState<any | null>(null);

    const generateReport = async () => {
        try {
            const html = `
            <html>
              <head>
                <style>
                  body { font-family: 'Helvetica'; padding: 20px; color: #333; }
                  h1 { color: #E91E63; text-align: center; }
                  .header { display: flex; justify-content: space-between; margin-bottom: 20px; border-bottom: 2px solid #E91E63; padding-bottom: 10px; }
                  .section { margin-bottom: 15px; background: #FFF0F5; padding: 10px; border-radius: 8px; }
                  .label { font-weight: bold; color: #555; }
                  .value { color: #000; }
                  .footer { margin-top: 30px; font-size: 12px; color: #888; text-align: center; }
                </style>
              </head>
              <body>
                <div class="header">
                   <div>
                     <h1>PCOS Metabolic Report</h1>
                     <p>Generated by Luna Companion</p>
                   </div>
                   <div>
                     <p>Date: ${new Date().toLocaleDateString()}</p>
                   </div>
                </div>

                <div class="section">
                  <h3>Patient Analysis</h3>
                  <p><span class="label">Facial Analysis:</span> ${analysis?.pcosScore ? analysis.pcosScore + '/100 PCO-S Risk' : 'Not analyzed'}</p>
                  <p><span class="label">Hirsutism Score:</span> ${analysis?.analysis?.hirsutism?.severity_score || 'N/A'}</p>
                  <p><span class="label">Acne Grade:</span> ${analysis?.analysis?.acne?.severity_score || 'N/A'}</p>
                </div>

                <div class="section">
                   <h3>Metabolic Insights (Synthetic)</h3>
                   <p><span class="label">Insulin Resistance:</span> Moderate (Estimated)</p>
                   <p><span class="label">Cortisol Levels:</span> Elevated in mornings</p>
                   <p><span class="label">Sleep Quality:</span> 7.2 hrs (Avg)</p>
                </div>

                <div class="section">
                   <h3>Recommendations</h3>
                   <ul>
                     <li>Consider low GI breakfast options.</li>
                     <li>Monitor androgen levels with a clinical test.</li>
                     <li>Daily spearmint tea recommended for hirsutism management.</li>
                   </ul>
                </div>

                <div class="footer">
                  This report is AI-generated and for informational purposes only. Please consult a doctor for diagnosis.
                </div>
              </body>
            </html>
            `;

            const { uri } = await Print.printToFileAsync({ html });
            await Sharing.shareAsync(uri);
        } catch (error) {
            Alert.alert("Error", "Could not generate report");
            console.error(error);
        }
    };

    const takePhoto = async () => {
        const { status } = await ImagePicker.requestCameraPermissionsAsync();
        if (status !== 'granted') {
            Alert.alert("Permission Denied", "Camera access is needed.");
            return;
        }

        let result = await ImagePicker.launchCameraAsync({
            allowsEditing: true,
            aspect: [4, 4],
            quality: 0.5,
            base64: true,
        });

        if (!result.canceled && result.assets && result.assets.length > 0) {
            setImage(result.assets[0].uri);
            analyzeFace(result.assets[0].base64);
        }
    };

    const pickImage = async () => {
        let result = await ImagePicker.launchImageLibraryAsync({
            mediaTypes: ImagePicker.MediaTypeOptions.Images,
            allowsEditing: true,
            aspect: [4, 4],
            quality: 0.5,
            base64: true,
        });

        if (!result.canceled && result.assets && result.assets.length > 0) {
            setImage(result.assets[0].uri);
            analyzeFace(result.assets[0].base64);
        }
    };

    const analyzeFace = async (base64: string | undefined | null) => {
        if (!base64) return;
        setLoading(true);
        setAnalysis(null);

        try {
            const response = await fetch(API_ENDPOINTS.FACIAL_ANALYZE, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ imageBase64: base64 }),
            });

            const data = await response.json();

            if (data.success) {
                setAnalysis(data);
            } else {
                Alert.alert("Error", data.error || "Analysis failed");
            }
        } catch (error) {
            Alert.alert("Connection Error", "Could not reach the AI server.");
        } finally {
            setLoading(false);
        }
    };

    const renderScoreBar = (score: number, label: string) => (
        <View style={styles.scoreRow}>
            <Text style={styles.scoreLabel}>{label}</Text>
            <View style={styles.barContainer}>
                <View style={[styles.barFill, { width: `${(score / 4) * 100}%` }]} />
            </View>
            <Text style={styles.scoreValue}>{score}/4</Text>
        </View>
    );

    return (
        <ScreenWrapper>
            <ScrollView contentContainerStyle={styles.container}>
                <View style={styles.header}>
                    <Text style={styles.title}>Facial Phenotype Analysis</Text>
                    <Text style={styles.subtitle}>Upload a selfie to screen for hirsutism & acne patterns</Text>
                </View>

                {/* Upload Section */}
                {/* Upload Options */}
                <View style={styles.actionContainer}>
                    <TouchableOpacity style={styles.actionButton} onPress={takePhoto}>
                        <View style={[styles.iconCircle, { backgroundColor: '#E3F2FD' }]}>
                            <Ionicons name="camera" size={28} color={COLORS.primary} />
                        </View>
                        <Text style={styles.actionText}>Take Selfie</Text>
                    </TouchableOpacity>

                    <TouchableOpacity style={styles.actionButton} onPress={pickImage}>
                        <View style={[styles.iconCircle, { backgroundColor: '#F3E5F5' }]}>
                            <Ionicons name="images" size={28} color={COLORS.secondary} />
                        </View>
                        <Text style={styles.actionText}>Gallery</Text>
                    </TouchableOpacity>
                </View>

                {image && (
                    <View style={styles.previewContainer}>
                        <Image source={{ uri: image }} style={styles.previewImage} />
                        <TouchableOpacity style={styles.retakeButton} onPress={() => setImage(null)}>
                            <Ionicons name="close-circle" size={24} color={COLORS.error} />
                        </TouchableOpacity>
                    </View>
                )}

                {loading && (
                    <View style={styles.loadingBox}>
                        <ActivityIndicator size="large" color={COLORS.primary} />
                        <Text style={styles.loadingText}>Scanning facial markers...</Text>
                    </View>
                )}

                {/* Results Section */}
                {analysis && !loading && (
                    <Animated.View entering={FadeInUp.duration(600)}>

                        {/* Summary Card */}
                        <View style={styles.resultCard}>
                            <Text style={styles.cardTitle}>Diagnostic Summary</Text>
                            <View style={styles.summaryRow}>
                                <View style={styles.summaryItem}>
                                    <Text style={styles.bigNumber}>{analysis.pcosScore.totalHirsutismScore}</Text>
                                    <Text style={styles.smallLabel}>Hirsutism Score</Text>
                                </View>
                                <View style={styles.divider} />
                                <View style={styles.summaryItem}>
                                    <Text style={styles.bigNumber}>{analysis.analysis.acne?.gagsScore || 0}</Text>
                                    <Text style={styles.smallLabel}>Acne Grade</Text>
                                </View>
                            </View>
                            <Text style={styles.analysisText}>
                                {analysis.analysis.hyperandrogenismIndicator?.reasoning}
                            </Text>
                        </View>

                        {/* Detailed Breakdown */}
                        <View style={styles.section}>
                            <Text style={styles.sectionHeader}>Hirsutism Breakdown</Text>
                            {renderScoreBar(analysis.analysis.hirsutism.upperLip.score, "Upper Lip")}
                            {renderScoreBar(analysis.analysis.hirsutism.chin.score, "Chin")}
                            {renderScoreBar(analysis.analysis.hirsutism.sideburns.score, "Jawline")}
                        </View>

                        {/* Quality Check */}
                        <View style={styles.qualityTag}>
                            <Ionicons name="checkmark-circle" size={16} color="green" />
                            <Text style={styles.qualityText}>
                                Image Quality: {analysis.analysis.imageQuality?.adequate ? "Good" : "Poor"}
                            </Text>
                        </View>

                    </Animated.View>
                )}
            </ScrollView>

            <TouchableOpacity
                style={{
                    position: 'absolute',
                    bottom: 20,
                    right: 20,
                    backgroundColor: COLORS.primary,
                    paddingHorizontal: 20,
                    paddingVertical: 12,
                    borderRadius: 25,
                    flexDirection: 'row',
                    alignItems: 'center',
                    ...SHADOWS.soft
                }}
                onPress={generateReport}
            >
                <Ionicons name="document-text" size={20} color={COLORS.white} style={{ marginRight: 8 }} />
                <Text style={{ color: COLORS.white, fontWeight: 'bold' }}>Download Report</Text>
            </TouchableOpacity>
        </ScreenWrapper>
    );
};

const styles = StyleSheet.create({
    container: { padding: 20, paddingBottom: 100 },
    header: { marginBottom: 20 },
    title: { ...FONTS.h2, color: COLORS.text },
    subtitle: { ...FONTS.body3, color: COLORS.gray, marginTop: 5 },
    uploadBox: {
        height: 250,
        backgroundColor: '#FFF',
        borderRadius: 20,
        overflow: 'hidden',
        ...SHADOWS.soft,
        marginBottom: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    previewImage: { width: '100%', height: '100%' },
    placeholder: { alignItems: 'center' },
    uploadText: { color: COLORS.primary, marginTop: 10, fontWeight: '600' },
    loadingBox: { alignItems: 'center', marginVertical: 20 },
    loadingText: { marginTop: 10, color: COLORS.gray },
    resultCard: {
        backgroundColor: COLORS.white,
        padding: 20,
        borderRadius: 20,
        ...SHADOWS.soft,
        marginBottom: 20,
    },
    cardTitle: { ...FONTS.h3, marginBottom: 15 },
    summaryRow: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 15 },
    summaryItem: { alignItems: 'center' },
    divider: { width: 1, backgroundColor: '#EEE' },
    bigNumber: { fontSize: 32, fontWeight: 'bold', color: COLORS.primary },
    smallLabel: { fontSize: 12, color: COLORS.gray },
    analysisText: { ...FONTS.body3, color: COLORS.text, lineHeight: 20 },
    section: { marginBottom: 20 },
    sectionHeader: { ...FONTS.h3, marginBottom: 10 },
    scoreRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    scoreLabel: { width: 80, fontSize: 14, color: COLORS.text },
    barContainer: { flex: 1, height: 8, backgroundColor: '#EEE', borderRadius: 4, marginHorizontal: 10 },
    barFill: { height: '100%', backgroundColor: COLORS.secondary, borderRadius: 4 },
    scoreValue: { width: 30, fontSize: 14, fontWeight: 'bold', textAlign: 'right' },
    qualityTag: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', opacity: 0.7 },
    qualityText: { marginLeft: 5, fontSize: 12, color: COLORS.gray },
    actionContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
        gap: 15,
    },
    actionButton: {
        flex: 1,
        backgroundColor: COLORS.white,
        borderRadius: 15,
        padding: 20,
        alignItems: 'center',
        ...SHADOWS.soft,
    },
    iconCircle: {
        width: 50,
        height: 50,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
    },
    actionText: {
        ...FONTS.h3,
        fontSize: 14,
        color: COLORS.text,
    },
    previewContainer: {
        height: 300,
        backgroundColor: COLORS.white,
        borderRadius: 20,
        ...SHADOWS.soft,
        marginBottom: 20,
        overflow: 'hidden',
    },
    retakeButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: 'rgba(255,255,255,0.8)',
        borderRadius: 15,
        padding: 2,
    },
});
